name: Python package

on: [pull_request]

jobs:
  upload:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: yaananth/twine-upload@tv1
      with:
        repo: nimport
    - name: Fail
      run: |
        failing
